blank_issues_enabled: true
contact_links:
  - name: Soporte Comunitario
    url: https://github.com/JesusAraujoDEV/mediart
    about: ¿Tienes preguntas o necesitas ayuda? Visita nuestras discusiones.
    